Avency:
  Neos:
    Etracker:
      blockCookies: true
Neos:
  Neos:
    fusion:
      autoInclude:
        'Avency.Neos.Etracker': true
    userInterface:
      translation:
        autoInclude:
          'Avency.Neos.Etracker':
            - 'NodeTypes/*'
